language: node_js
node_js:
  - "7"
branches:
  only:
  - master
before_script:
  - npm install
script:
  - npm test & npm run build
after_success:
  - "find ./dist -name '*' -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://$FTP_HOST \\;"

